### ISSUE TITLE
Duplicating ID Datawatcher Crash

### ISSUE THREAD

**Issue by Emirhangg** [Ckathode/balkons-weaponmod#13]
Time: 28.12.2015 18:38
Description: Ticking memory connection

java.lang.IllegalArgumentException: Duplicate id value for 26!
    at net.minecraft.entity.DataWatcher.func_75682_a(SourceFile:64)
    at ckathode.weaponmod.PlayerWeaponData.initPlayerWeaponData(PlayerWeaponData.java:23)
    at ckathode.weaponmod.WMCommonEventHandler.onEntityConstructed(WMCommonEventHandler.java:14)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_428_WMCommonEventHandler_onEntityConstructed_EntityConstructing.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraft.entity.Entity.<init>(Entity.java:179)
    at net.minecraft.entity.EntityLivingBase.<init>(EntityLivingBase.java:119)
    at net.minecraft.entity.player.EntityPlayer.<init>(EntityPlayer.java:141)
    at net.minecraft.entity.player.EntityPlayerMP.<init>(EntityPlayerMP.java:138)
    at net.minecraft.server.management.ServerConfigurationManager.func_148545_a(ServerConfigurationManager.java:410)
    at net.minecraft.server.network.NetHandlerLoginServer.func_147326_c(NetHandlerLoginServer.java:101)
    at net.minecraft.server.network.NetHandlerLoginServer.func_147233_a(NetHandlerLoginServer.java:60)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:215)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.entity.DataWatcher.func_75682_a(SourceFile:64)
    at ckathode.weaponmod.PlayerWeaponData.initPlayerWeaponData(PlayerWeaponData.java:23)
    at ckathode.weaponmod.WMCommonEventHandler.onEntityConstructed(WMCommonEventHandler.java:14)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_428_WMCommonEventHandler_onEntityConstructed_EntityConstructing.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraft.entity.Entity.<init>(Entity.java:179)
    at net.minecraft.entity.EntityLivingBase.<init>(EntityLivingBase.java:119)
    at net.minecraft.entity.player.EntityPlayer.<init>(EntityPlayer.java:141)
    at net.minecraft.entity.player.EntityPlayerMP.<init>(EntityPlayerMP.java:138)
    at net.minecraft.server.management.ServerConfigurationManager.func_148545_a(ServerConfigurationManager.java:410)
    at net.minecraft.server.network.NetHandlerLoginServer.func_147326_c(NetHandlerLoginServer.java:101)
    at net.minecraft.server.network.NetHandlerLoginServer.func_147233_a(NetHandlerLoginServer.java:60)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:215)

-- Ticking connection --
Details:
    Connection: net.minecraft.network.NetworkManager@3c2670
Stacktrace:
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (x86) version 6.1
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 63867576 bytes (60 MB) / 523501568 bytes (499 MB) up to 523501568 bytes (499 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 Optifine OptiFine_1.7.10_HD_U_C1 104 mods loaded, 104 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1558-1.7.10.jar) 
    UCHIJAAAA   Forge{10.13.4.1558} [Minecraft Forge](forge-1.7.10-10.13.4.1558-1.7.10.jar) 
    UCHIJAAAA   appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core](minecraft.jar) 
    UCHIJAAAA   CodeChickenCore{1.0.4.29} [CodeChicken Core](minecraft.jar) 
    UCHIJAAAA   itemphysic{1.1.2} [ItemPhysic](minecraft.jar) 
    UCHIJAAAA   NotEnoughItems{1.0.3.74} [Not Enough Items](NotEnoughItems-1.7.10-1.0.3.74-universal.jar) 
    UCHIJAAAA   <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCHIJAAAA   bspkrsCore{6.16} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.16.jar) 
    UCHIJAAAA   Treecapitator{1.7.10} [Treecapitator]([1.7.10]Treecapitator-universal-2.0.4.jar) 
    UCHIJAAAA   CoFHCore{1.7.10R3.0.3} [CoFH Core](CoFHCore-[1.7.10]3.0.3-303.jar) 
    UCHIJAAAA   BuildCraft|Core{7.1.14} [BuildCraft](buildcraft-7.1.14.jar) 
    UCHIJAAAA   BuildCraft|Transport{7.1.14} [BC Transport](buildcraft-7.1.14.jar) 
    UCHIJAAAA   BuildCraft|Silicon{7.1.14} [BC Silicon](buildcraft-7.1.14.jar) 
    UCHIJAAAA   BuildCraft|Factory{7.1.14} [BC Factory](buildcraft-7.1.14.jar) 
    UCHIJAAAA   ComputerCraft{1.74} [ComputerCraft](ComputerCraftPlusComputerCraftEdu1.74.jar) 
    UCHIJAAAA   factorization.notify{1.0} [Factorization Notification System](Factorization-1.7.10-0.8.101.jar) 
    UCHIJAAAA   factorization.dimensionalSlice{0.8.101} [Factorization Dimensional Slices](Factorization-1.7.10-0.8.101.jar) 
    UCHIJAAAA   factorization{0.8.101} [Factorization](Factorization-1.7.10-0.8.101.jar) 
    UCHIJAAAA   IC2{2.2.810-experimental} [IndustrialCraft 2](industrialcraft-2-2.2.810-experimental.jar) 
    UCHIJAAAA   ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation](ThermalFoundation-[1.7.10]1.2.0-102.jar) 
    UCHIJAAAA   ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
    UCHIJAAAA   LogisticsPipes{0.9.3.70} [Logistics Pipes](logisticspipes-0.9.3.70.jar) 
    UCHIJAAAA   additionalpipes{4.7.0} [Additional Pipes](additionalpipes-4.7.0.jar) 
    UCHIJAAAA   ImmibisCore{59.1.4} [Immibis Core](immibis-core-59.1.4.jar) 
    UCHIJAAAA   AdvancedRepulsionSystems{59.0.4} [Advanced Repulsion Systems](adv-repulsion-systems-59.0.4.jar) 
    UCHIJAAAA   advancedcapes{1.4} [AdvancedCapes Mod](advancedcapes-1.4.jar) 
    UCHIJAAAA   appliedenergistics2{rv2-stable-10} [Applied Energistics 2](appliedenergistics2-rv2-stable-10.jar) 
    UCHIJAAAA   BuildCraft|Builders{7.1.14} [BC Builders](buildcraft-7.1.14.jar) 
    UCHIJAAAA   BuildCraft|Energy{7.1.14} [BC Energy](buildcraft-7.1.14.jar) 
    UCHIJAAAA   BuildCraft|Robotics{7.1.14} [BC Robotics](buildcraft-7.1.14.jar) 
    UCHIJAAAA   BuildCraft|Compat{7.1.3} [BuildCraft Compat](buildcraft-compat-7.1.3 %281%29.jar) 
    UCHIJAAAA   CompactSolars{4.4.39.315} [Compact Solar Arrays](CompactSolars-1.7.10-4.4.39.315-universal.jar) 
    UCHIJAAAA   ComputerCraftEdu{1.74} [ComputerCraftEdu](ComputerCraftPlusComputerCraftEdu1.74.jar) 
    UCHIJAAAA   creativecore{1.0} [CreativeCore](CreativeCore v1.1.4 mc1.7.10.jar) 
    UCHIJAAAA   DamageIndicatorsMod{3.2.0} [Damage Indicators](Damage-Indicators-Mod-1.7.10.jar) 
    UCHIJAAAA   DimensionalAnchors{59.0.3} [Dimensional Anchors](dimensional-anchor-59.0.3.jar) 
    UCHIJAAAA   dimdoors{2.2.5-test9} [Dimensional Doors](DimensionalDoors-2.2.5-test9.jar) 
    UCHIJAAAA   Doca{1.7.4_2.2.7} [DogCatPlus](Dog-Cat-Plus-Mod-1.7.10.jar) 
    UCHIJAAAA   EnderStorage{1.4.5.27} [EnderStorage](EnderStorage-1.7.10-1.4.5.27-universal.jar) 
    UCHIJAAAA   EE3{0.3.507} [Equivalent Exchange 3](EquivalentExchange3-1.7.10-0.3.507.jar) 
    UCHIJAAAA   factorization.misc{0.8.101} [Factorization Miscellaneous Nonsense](Factorization-1.7.10-0.8.101.jar) 
    UCHIJAAAA   fz.scrap{0.8.101} [Scrap](Factorization-1.7.10-0.8.101.jar) 
    UCHIJAAAA   factorization.truth{0.8.101} [Truth](Factorization-1.7.10-0.8.101.jar) 
    UCHIJAAAA   FlatBedrockx{1.0.2} [FlatBedrock Xplosion's Edition](FlatBedrock-1.0.2.jar) 
    UCHIJAAAA   IC2NuclearControl{2.3.3a-Exist} [Nuclear Control 2](IC2NuclearControl-2.3.3a-Exist.jar) 
    UCHIJAAAA   inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks](InventoryTweaks-1.59-dev-152.jar) 
    UCHIJAAAA   MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   Mystcraft{0.12.3.01} [Mystcraft](mystcraft-1.7.10-0.12.3.01.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   ForgeMultipart{1.2.0.345} [Forge Multipart](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHIJAAAA   MrTJPCoreMod{1.1.0.31} [MrTJPCore](MrTJPCore-1.1.0.31-universal.jar) 
    UCHIJAAAA   ProjRed|Core{4.7.0pre9.92} [ProjectRed Core](ProjectRed-1.7.10-4.7.0pre9.92-Base.jar) 
    UCHIJAAAA   ProjRed|Exploration{4.7.0pre9.92} [ProjectRed Exploration](ProjectRed-1.7.10-4.7.0pre9.92-World.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   numina{0.4.0.119} [Numina](Numina-0.4.0.119.jar) 
    UCHIJAAAA   powersuits{0.11.0.294} [MachineMuse's Modular Powersuits](ModularPowersuits-0.11.0.294.jar) 
    UCHIJAAAA   MouseTweaks{2.4.4} [Mouse Tweaks](MouseTweaks-2.4.4-mc1.7.10 %282%29.jar) 
    UCHIJAAAA   NEIAddons{1.12.14.40} [NEI Addons](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|Developer{1.12.14.40} [NEI Addons: Developer Tools](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|AppEng{1.12.14.40} [NEI Addons: Applied Energistics 2](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|Botany{1.12.14.40} [NEI Addons: Botany](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|Forestry{1.12.14.40} [NEI Addons: Forestry](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|CraftingTables{1.12.14.40} [NEI Addons: Crafting Tables](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|ExNihilo{1.12.14.40} [NEI Addons: Ex Nihilo](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHIJAAAA   NetherOres{1.7.10R2.3.0} [Nether Ores](NetherOres-[1.7.10]2.3.0-12.jar) 
    UCHIJAAAA   PowerConverters3{1.7.10-2.11} [Power Converters 3](PowerConverters-1.7.10-2.11.jar) 
    UCHIJAAAA   ProjRed|Transmission{4.7.0pre9.92} [ProjectRed Transmission](ProjectRed-1.7.10-4.7.0pre9.92-Integration.jar) 
    UCHIJAAAA   ProjRed|Transportation{4.7.0pre9.92} [ProjectRed Transportation](ProjectRed-1.7.10-4.7.0pre9.92-Mechanical.jar) 
    UCHIJAAAA   ProjRed|Compatibility{4.7.0pre9.92} [ProjectRed Compatibility](ProjectRed-1.7.10-4.7.0pre9.92-Compat.jar) 
    UCHIJAAAA   ProjRed|Integration{4.7.0pre9.92} [ProjectRed Integration](ProjectRed-1.7.10-4.7.0pre9.92-Integration.jar) 
    UCHIJAAAA   ProjRed|Fabrication{4.7.0pre9.92} [ProjectRed Fabrication](ProjectRed-1.7.10-4.7.0pre9.92-Fabrication.jar) 
    UCHIJAAAA   ProjRed|Illumination{4.7.0pre9.92} [ProjectRed Illumination](ProjectRed-1.7.10-4.7.0pre9.92-Lighting.jar) 
    UCHIJAAAA   ProjRed|Expansion{4.7.0pre9.92} [ProjectRed Expansion](ProjectRed-1.7.10-4.7.0pre9.92-Mechanical.jar) 
    UCHIJAAAA   ragdollCorpses{0.12} [Ragdoll Corpses](ragdollCorpses-0.12 for 1.7.10.jar) 
    UCHIJAAAA   ReiMinimap{1.7.10} [Rei's Minimap](reis-minimap-mod-1.7.10.jar) 
    UCHIJAAAA   StevesCarts{2.0.0.b18} [Steve's Carts 2](StevesCarts2.0.0.b18.jar) 
    UCHIJAAAA   Tubestuff{59.0.4} [Tubestuff](tubestuff-59.0.4.jar) 
    UCHIJAAAA   weaponmod{v1.14.3} [Balkon's WeaponMod](weaponmod-1.14.3.jar) 
    UCHIJAAAA   WR-CBE|Core{1.4.1.9} [WR-CBE Core](WR-CBE-1.7.10-1.4.1.9-universal.jar) 
    UCHIJAAAA   WR-CBE|Addons{1.4.1.9} [WR-CBE Addons](WR-CBE-1.7.10-1.4.1.9-universal.jar) 
    UCHIJAAAA   WR-CBE|Logic{1.4.1.9} [WR-CBE Logic](WR-CBE-1.7.10-1.4.1.9-universal.jar) 
    UCHIJAAAA   McMultipart{1.2.0.345} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHIJAAAA   ForgeRelocation{0.0.1.4} [ForgeRelocation](ForgeRelocation-0.0.1.4-universal.jar) 
    UCHIJAAAA   MCFrames{1.0} [MCFrames](ForgeRelocation-0.0.1.4-universal.jar) 
    UCHIJAAAA   RelocationFMP{0.0.1.2} [RelocationFMP](ForgeRelocationFMP-0.0.1.2-universal.jar) 
    UCHIJAAAA   libsandstone{1.0.0} [libsandstone](LibSandstone-1.0.0.jar) 
    UCHIJAAAA   ForgeMicroblock{1.2.0.345} [Forge Microblocks](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    CoFHCore: -[1.7.10]3.0.3-303
    ThermalFoundation: -[1.7.10]1.2.0-102
    ThermalExpansion: -[1.7.10]4.0.3B1-218
    AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
    MineFactoryReloaded: -[1.7.10]2.8.0-104
    NetherOres: -[1.7.10]2.3.0-12
    AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:OFF, BC:ON, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:ON, FMP:ON, RB:OFF, CLApi:OFF, Waila:OFF, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 0 / 8; []
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Emirhangg** [comment]
Yes, i getting this crash, can anyone help me?
